# -*- coding: utf-8 -*-
"""Mini_Hack3(600258_Siwat)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13O2Lkpo3pAHJKxS9HSQVDHe-Q2rM9418

# FahMai RAG V2-Ensemble — Majority Voting

**Strategy:** รัน V2 (0.73 proven) 3 รอบ ด้วย 3 prompt styles ต่างกัน
แล้วเอาคำตอบมาโหวต — ข้อไหน 2/3 ตรงกัน ใช้คำตอบนั้น

ไม่เปลี่ยน pipeline, ไม่เปลี่ยน retrieval, ไม่เพิ่ม reranker
เปลี่ยนแค่ prompt style → ลด hallucination

## Section 0: Setup
"""

!pip install -q sentence-transformers pythainlp rank-bm25 requests
!pip install -q -U transformers

# !kaggle competitions download (Kaggle only)
# --- Colab: Upload zip file ---
from google.colab import files
print("Upload super-ai-engineer-s-6-fah-mai-rag-challenge-level-1.zip")
uploaded = files.upload()
!unzip -qo super-ai-engineer-s-6-fah-mai-rag-challenge-level-1.zip

import os, csv, re, time, requests, json
import numpy as np
from pathlib import Path
from collections import defaultdict, Counter

N_QUESTIONS      = 100
DATA_DIR         = "data"
KB_DIR           = f"{DATA_DIR}/knowledge_base"
QUESTIONS_FILE   = f"{DATA_DIR}/questions.csv"

CHUNK_SIZE       = 800
CHUNK_OVERLAP    = 150
TOP_K_RETRIEVE   = 10
TOP_K_FINAL      = 5         # เก็บ 5 เหมือน V2 (proven)
RRF_K            = 60

EMBED_MODEL_NAME = "BAAI/bge-m3"
LLM_MODEL        = "typhoon"
LLM_TEMPERATURE  = 0

try:
    from kaggle_secrets import UserSecretsClient
    THAILLM_API_KEY = UserSecretsClient().get_secret("ThaiLLM")
except:
    try:
        from google.colab import userdata
        THAILLM_API_KEY = userdata.get('ThaiLLM')
    except:
        THAILLM_API_KEY = os.environ.get("THAILLM_API_KEY", "YOUR_KEY")

print(f"Embed: {EMBED_MODEL_NAME} | LLM: {LLM_MODEL}")
print(f"API key: {'SET' if THAILLM_API_KEY != 'YOUR_KEY' else 'MISSING!'}")

"""## Section 1: API (same as V2)

"""

def _call_llm_api(messages, model, max_retries=5, temperature=0):
    url = f"http://thaillm.or.th/api/{model}/v1/chat/completions"
    headers = {"Content-Type": "application/json", "apikey": THAILLM_API_KEY}
    payload = {"model": "/model", "messages": messages,
               "max_tokens": 2048, "temperature": temperature}
    for attempt in range(max_retries):
        try:
            resp = requests.post(url, headers=headers, json=payload, timeout=180)
            if resp.status_code == 429:
                time.sleep(min(2 ** attempt, 30))
                continue
            resp.raise_for_status()
            return resp.json()["choices"][0]["message"]["content"].strip()
        except requests.exceptions.RequestException as e:
            time.sleep(2 ** attempt)
            print(f"  Error ({model}): {e}")
    return None


def ask_llm(messages, model=LLM_MODEL, max_retries=5, temperature=LLM_TEMPERATURE):
    result = _call_llm_api(messages, model, max_retries, temperature)
    if result is not None:
        return result
    for fb in ["openthaigpt", "kbtg", "pathumma"]:
        if fb == model:
            continue
        print(f"  >> Fallback: {fb}")
        result = _call_llm_api(messages, fb, max_retries=3, temperature=temperature)
        if result is not None:
            return result
    return None


def parse_answer(text):
    if text is None:
        return None
    clean = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL).strip()
    m = re.search(r"ANSWER:\s*(\d{1,2})", clean)
    if m:
        val = int(m.group(1))
        if 1 <= val <= 10:
            return val
    for d in re.findall(r"\b(\d{1,2})\b", clean):
        if 1 <= int(d) <= 10:
            return int(d)
    return None

"""## Section 2: KB & Chunking (same as V2)

"""

def extract_doc_metadata(filepath, text):
    path_str = str(filepath)
    meta = {"path": path_str, "product": "", "brand": "", "category": ""}
    h1 = re.search(r"^#\s+(.+)", text, re.MULTILINE)
    if h1:
        meta["product"] = h1.group(1).strip()
    brands = {
        "saifah": "SaiFah (สายฟ้า)", "daonuea": "DaoNuea (ดาวเหนือ)",
        "kluensiang": "KluenSiang (คลื่นเสียง)", "wongkhojon": "WongKhoJon (วงโคจร)",
        "judchuem": "JudChuem (จุดเชื่อม)", "judchuam": "JudChuem (จุดเชื่อม)",
        "novatech": "NovaTech", "zenbyte": "ZenByte",
        "pulsegear": "PulseGear", "arcwave": "ArcWave",
    }
    for key, name in brands.items():
        if key in path_str.lower() or key in text.lower():
            meta["brand"] = name
            break
    cats = {
        "phone": "สมาร์ทโฟน", "โฟน": "สมาร์ทโฟน", "tablet": "แท็บเล็ต",
        "แท็บ": "แท็บเล็ต", "pad": "แท็บเล็ต", "laptop": "แล็ปท็อป",
        "notebook": "แล็ปท็อป", "book": "แล็ปท็อป", "headphone": "หูฟัง",
        "earbuds": "หูฟัง", "buds": "หูฟัง", "เฮด": "หูฟัง",
        "watch": "สมาร์ทวอทช์", "band": "สมาร์ทแบนด์",
        "speaker": "ลำโพง", "soundbar": "ซาวด์บาร์", "sound": "ลำโพง/ซาวด์บาร์",
        "charger": "อุปกรณ์ชาร์จ", "hub": "อุปกรณ์เชื่อมต่อ",
        "dock": "อุปกรณ์เชื่อมต่อ", "monitor": "จอภาพ",
        "policy": "นโยบาย", "shipping": "การจัดส่ง", "member": "สมาชิก",
    }
    for key, cat in cats.items():
        if key in text.lower() or key in path_str.lower():
            meta["category"] = cat
            break
    return meta


def chunk_by_markdown(text, metadata, chunk_size=CHUNK_SIZE, overlap=CHUNK_OVERLAP):
    parts = []
    if metadata.get("product"): parts.append(metadata["product"])
    if metadata.get("brand"): parts.append(metadata["brand"])
    if metadata.get("category"): parts.append(metadata["category"])
    prefix = f"[{' | '.join(parts)}]\n" if parts else ""
    sections = re.split(r"\n(?=##\s)", text)
    if len(sections) <= 1:
        sections = text.split("\n\n")
    chunks = []
    current = ""
    for sec in sections:
        sec = sec.strip()
        if not sec:
            continue
        if len(current) + len(sec) + 2 <= chunk_size:
            current = (current + "\n\n" + sec).strip()
        else:
            if current.strip():
                chunks.append(prefix + current.strip())
            if len(sec) <= chunk_size:
                current = sec
            else:
                paragraphs = sec.split("\n")
                sub = ""
                for p in paragraphs:
                    if len(sub) + len(p) + 1 <= chunk_size:
                        sub = (sub + "\n" + p).strip()
                    else:
                        if sub.strip():
                            chunks.append(prefix + sub.strip())
                        sub = p
                current = sub.strip() if sub.strip() else ""
    if current.strip():
        chunks.append(prefix + current.strip())
    if not chunks:
        chunks = [prefix + text.strip()]
    return chunks


kb_dir = Path(KB_DIR)
documents = []
all_chunks = []
for fp in sorted(kb_dir.rglob("*.md")):
    text = fp.read_text(encoding="utf-8")
    rel = fp.relative_to(kb_dir)
    meta = extract_doc_metadata(rel, text)
    documents.append({"path": str(rel), "text": text, "metadata": meta})
    for ct in chunk_by_markdown(text, meta):
        all_chunks.append({"text": ct, "source": str(rel),
                           "product": meta.get("product", ""), "brand": meta.get("brand", "")})
print(f"Loaded {len(documents)} docs → {len(all_chunks)} chunks")

"""## Section 3: Indices

"""

from sentence_transformers import SentenceTransformer

print(f"Loading {EMBED_MODEL_NAME}...")
embed_model = SentenceTransformer(EMBED_MODEL_NAME)
chunk_texts = [c["text"] for c in all_chunks]
print(f"Embedding {len(chunk_texts)} chunks...")
chunk_embeddings = embed_model.encode(chunk_texts, normalize_embeddings=True,
                                       show_progress_bar=True, batch_size=16)
print(f"Shape: {chunk_embeddings.shape}")

from pythainlp.tokenize import word_tokenize
from rank_bm25 import BM25Okapi

tokenized_chunks = [word_tokenize(c["text"], engine="newmm") for c in all_chunks]
bm25 = BM25Okapi(tokenized_chunks)
print(f"BM25: {len(tokenized_chunks)} chunks")

"""## Section 4: Retrieval (same as V2)

"""

def dense_retrieve(query, k=TOP_K_RETRIEVE):
    q_emb = embed_model.encode([query], normalize_embeddings=True)
    scores = (chunk_embeddings @ q_emb.T).flatten()
    top_idx = np.argsort(scores)[::-1][:k]
    return top_idx, scores[top_idx]

def bm25_retrieve(query, k=TOP_K_RETRIEVE):
    tokens = word_tokenize(query, engine="newmm")
    scores = bm25.get_scores(tokens)
    top_idx = np.argsort(scores)[::-1][:k]
    return top_idx, scores[top_idx]

def hybrid_retrieve(query, k=TOP_K_FINAL, rrf_k=RRF_K):
    dense_idx, _ = dense_retrieve(query, k=TOP_K_RETRIEVE)
    bm25_idx, _ = bm25_retrieve(query, k=TOP_K_RETRIEVE)
    rrf = defaultdict(float)
    for rank, idx in enumerate(dense_idx):
        rrf[idx] += 1.0 / (rrf_k + rank + 1)
    for rank, idx in enumerate(bm25_idx):
        rrf[idx] += 1.0 / (rrf_k + rank + 1)
    sorted_idx = sorted(rrf.keys(), key=lambda x: rrf[x], reverse=True)
    return sorted_idx[:k], [rrf[i] for i in sorted_idx[:k]]

def retrieve_for_comparison(query, product_names, k_per_product=3):
    seen = set()
    retrieved = []
    h_idx, _ = hybrid_retrieve(query, k=TOP_K_FINAL)
    for idx in h_idx:
        seen.add(idx)
        retrieved.append(all_chunks[idx])
    for pname in product_names:
        tokens = word_tokenize(pname, engine="newmm")
        scores = bm25.get_scores(tokens)
        top = np.argsort(scores)[::-1][:k_per_product]
        for idx in top:
            if idx not in seen and scores[idx] > 0:
                seen.add(idx)
                retrieved.append(all_chunks[idx])
    return retrieved

"""## Section 5: Query Analysis (same as V2)

"""

PRODUCT_KEYWORDS = [
    "X9 Pro Max", "X9 Pro", "X9 FE", "X9", "V7 Lite", "V7",
    "Rugged R1", "Lite 3", "Senior Plus", "Kid Safe",
    "Tab S9 Pro", "Tab S8 Pro", "Tab A5", "DuoPad", "Draw Pro",
    "SaiFah Pen", "Pen Gen 2",
    "StormBook G9 Titan", "StormBook G9", "StormBook G7",
    "StormBook G5", "StormBook",
    "CreatorBook 16 OLED", "CreatorBook 16", "CreatorBook 14",
    "ProBook 16", "ProBook 14 Max", "ProBook 14",
    "AirBook 15", "AirBook 14", "AirBook 13",
    "FlexBook Detach", "FlexBook", "StudyBook 14 Plus", "StudyBook 14",
    "Mini PC M1",
    "HeadPro X1 SE", "HeadPro X1", "HeadOn 700", "HeadOn 500", "HeadOn 300",
    "StudioPro M1", "GameStorm H1",
    "Buds Z5 Pro", "Buds Z5", "Sport X", "Sport Lite",
    "SoundBar Pro 500", "SoundBar 300",
    "Speaker S10", "Speaker M5",
    "Watch S3 Ultra", "Watch S3 Pro", "Watch S3 SE", "Watch S3",
    "Watch Sport G1", "Band 8 Pro", "Band 8",
    "Hub 7-in-1", "Hub 4-in-1", "QiPad 15", "QiPad Duo",
    "GaN 67W", "GaN 100W Dual", "Charger 30W",
    "Cable Pro", "Dock Pro", "Dock AirBook Edition",
    "NovaBuds Pro", "NovaBuds Lite", "SlimBook 14",
    "SoundPillar 300", "ProView 27 4K", "All-in-One 27",
    "ChargePad 15W", "Power Bank",
]
PRODUCT_KEYWORDS.sort(key=len, reverse=True)

NOT_RELATED_KEYWORDS = [
    "สูตรอาหาร", "ผัดกระเพรา", "ตั๋วเครื่องบิน",
    "ดอกเบี้ย", "เงินฝาก", "วันหยุดราชการ",
    "สภาพอากาศ", "หวย", "ฟุตบอล",
]
FAHMAI_KEYWORDS = [
    "ฟ้าใหม่", "fahmai", "สายฟ้า", "ดาวเหนือ", "คลื่นเสียง",
    "วงโคจร", "จุดเชื่อม", "novatech", "arcwave", "pulsegear", "zenbyte",
]
POLICY_KEYWORDS = [
    "คืนสินค้า", "เคลม", "ประกัน", "ยกเลิก", "คืนเงิน", "ซ่อม",
    "จัดส่ง", "ส่งสินค้า", "สมาชิก", "points", "แต้ม", "Point",
    "warranty", "return", "refund", "Care+", "trade-in", "เทิร์น",
]

def detect_products(query):
    found = []
    q = query.lower()
    for p in PRODUCT_KEYWORDS:
        if p.lower() in q:
            found.append(p)
            q = q.replace(p.lower(), "___")
    return found

def is_comparison(query):
    products = detect_products(query)
    comp = ["กับ", "เทียบ", "ต่างกัน", "เหมือนกัน", "ทั้งสอง", "ทั้งคู่",
            "ตัวไหน", "อันไหน", "vs", "รุ่นไหน", "เปรียบเทียบ"]
    return len(products) >= 2 or (len(products) >= 1 and any(w in query for w in comp))

def is_not_related(query):
    q = query.lower()
    if detect_products(query): return False
    if any(kw in q for kw in FAHMAI_KEYWORDS): return False
    return any(kw in q for kw in NOT_RELATED_KEYWORDS)

def extract_core_question(query):
    if len(query) < 200: return query
    products = detect_products(query)
    markers = ["ไหม", "มั้ย", "ครับ", "คะ", "ค่ะ", "เท่าไหร่", "กี่", "อะไร",
               "ยังไง", "ได้มั้ย", "ได้ไหม", "อยากรู้", "อยากทราบ", "?"]
    sentences = re.split(r'[.?!。\n]+', query)
    sentences = [s.strip() for s in sentences if s.strip()]
    if len(sentences) <= 2: return query
    relevant = []
    for s in sentences:
        has_q = any(m in s for m in markers)
        has_p = any(p.lower() in s.lower() for p in products) if products else False
        if has_q or has_p: relevant.append(s)
    if relevant:
        core = " ".join(relevant)
        for p in products:
            if p.lower() not in core.lower(): core = f"{p} {core}"
        return core
    return " ".join(sentences[-2:])

"""## Section 6: THREE Prompt Styles for Ensemble

**Style A**: V2 original (analytical, proven 0.73)
**Style B**: Keyword-focused (match specs precisely)
**Style C**: Chain-of-Thought (step-by-step reasoning)

"""

# === STYLE A: V2 Original (proven 0.73) ===
PROMPT_A_SYSTEM = """คุณเป็น AI Customer Service ของร้าน FahMai (ฟ้าใหม่) ร้านขายอุปกรณ์อิเล็กทรอนิกส์

กฎสำคัญในการตอบ:
1. ตอบจากข้อมูลใน Context ที่ให้มาเท่านั้น ห้ามใช้ความรู้ภายนอก
2. อ่านทุกตัวเลือก 1-10 อย่างละเอียด เทียบกับข้อมูลใน Context
3. เลือกตัวเลือกที่ตรงกับ Context มากที่สุด
4. ระวังตัวเลขให้ดี: ราคา สเปค จำนวน ต้องตรงกับ Context
5. ระวังชื่อรุ่น: อย่าสับสนระหว่างรุ่นที่ชื่อคล้ายกัน (เช่น X9 vs X9 Pro vs X9 Pro Max)

เมื่อไหร่ควรเลือกข้อ 9 "ไม่มีข้อมูลนี้ในฐานข้อมูล":
- เลือก 9 เฉพาะเมื่อ Context ไม่มีข้อมูลเกี่ยวกับสิ่งที่ถาม เลยจริงๆ
- ถ้า Context มีข้อมูลของสินค้าที่ถามอยู่ ให้พยายามเลือก 1-8 ที่ใกล้เคียงที่สุด

เมื่อไหร่ควรเลือกข้อ 10 "คำถามนี้ไม่เกี่ยวข้อง":
- เลือก 10 เฉพาะเมื่อคำถามไม่เกี่ยวกับสินค้า/บริการ/ร้าน FahMai เลย

ตอบในรูปแบบ:
REASON: [อธิบายสั้นๆ อ้างอิงข้อมูลจาก Context]
ANSWER: [หมายเลข 1-10]"""


# === STYLE B: Keyword Matching (เน้นจับตัวเลข/สเปคตรง) ===
PROMPT_B_SYSTEM = """คุณเป็นผู้เชี่ยวชาญตรวจสอบสเปคสินค้าของร้าน FahMai

วิธีตอบ:
1. อ่าน Context ให้ละเอียด จับ "ตัวเลข" และ "คำสำคัญ" ที่ตรงกับคำถาม
2. เทียบตัวเลข/คำสำคัญกับแต่ละตัวเลือก 1-8
3. เลือกตัวเลือกที่มีตัวเลขและรายละเอียดตรงกับ Context มากที่สุด
4. ถ้า Context ไม่มีข้อมูลที่ตรงกับคำถามเลย → เลือก 9
5. ถ้าคำถามไม่เกี่ยวกับร้าน FahMai หรือสินค้าอิเล็กทรอนิกส์ → เลือก 10

สำคัญ: ห้ามเดา ต้องมีหลักฐานจาก Context

ตอบ:
ANSWER: [1-10]"""


# === STYLE C: Chain-of-Thought (คิดทีละขั้น) ===
PROMPT_C_SYSTEM = """คุณเป็น AI ของร้าน FahMai ตอบคำถามลูกค้า

วิธีคิด (ทำทีละขั้น):
ขั้น 1: คำถามถามเรื่องอะไร? (สเปค/ราคา/นโยบาย/เปรียบเทียบ/อื่นๆ)
ขั้น 2: Context มีข้อมูลที่เกี่ยวข้องไหม? ถ้าไม่มี → ANSWER: 9
ขั้น 3: คำถามเกี่ยวกับ FahMai ไหม? ถ้าไม่เกี่ยวเลย → ANSWER: 10
ขั้น 4: ตัวเลือกไหนตรงกับข้อมูลใน Context มากที่สุด?

สำคัญ:
- ใช้ข้อมูลจาก Context เท่านั้น ห้ามเดา
- ระวังชื่อรุ่น: X9 ≠ X9 Pro ≠ X9 Pro Max
- ระวังตัวเลข: ราคา/สเปคต้องตรงเป๊ะ

ตอบ:
REASON: [วิเคราะห์สั้นๆ]
ANSWER: [1-10]"""


def build_prompt(question, choices, chunks):
    ctx_parts = []
    for i, c in enumerate(chunks):
        ctx_parts.append(f"--- เอกสาร {i+1} (จาก: {c.get('source','?')}) ---\n{c['text']}")
    context = "\n\n".join(ctx_parts)
    choices_text = "\n".join(f"{k}. {v}" for k, v in choices.items())
    return (
        f"=== ข้อมูลอ้างอิง (Context) ===\n{context}\n\n"
        f"=== คำถาม ===\n{question}\n\n"
        f"=== ตัวเลือก ===\n{choices_text}\n\n"
        f"จากข้อมูลอ้างอิง จงเลือกตัวเลือกที่ถูกต้องที่สุด\n"
        f"ANSWER:"
    )

"""## Section 7: Retrieve once, Generate 3 times

"""

def get_chunks_for_question(q):
    """Retrieve chunks once (reuse for all 3 prompt styles)."""
    question = q["question"]

    if is_not_related(question):
        return None  # will return 10

    products = detect_products(question)
    is_comp = is_comparison(question)
    is_policy = any(kw in question for kw in POLICY_KEYWORDS)
    search_q = extract_core_question(question)

    if is_comp and len(products) >= 2:
        retrieved = retrieve_for_comparison(search_q, products)
    else:
        idx, _ = hybrid_retrieve(search_q, k=TOP_K_FINAL)
        retrieved = [all_chunks[i] for i in idx]

    # Policy boost
    if is_policy:
        has_policy = any("polic" in c.get("source","").lower() or "นโยบาย" in c["text"] for c in retrieved)
        if not has_policy:
            b_idx, _ = bm25_retrieve(search_q, k=5)
            for pi in b_idx:
                src = all_chunks[pi].get("source","").lower()
                if any(p in src for p in ["polic", "shipping", "member", "warranty"]):
                    retrieved.append(all_chunks[pi])

    return retrieved


def generate_answer(question, choices, chunks, system_prompt):
    """Generate answer with one prompt style."""
    prompt = build_prompt(question, choices, chunks)
    raw = ask_llm([
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": prompt},
    ])
    return parse_answer(raw)


def majority_vote(answers):
    """Pick the answer that appears most. Tie → pick first occurrence."""
    valid = [a for a in answers if a is not None]
    if not valid:
        return 9
    counts = Counter(valid)
    # Most common answer
    winner, count = counts.most_common(1)[0]
    return winner


# Load questions
questions = []
with open(QUESTIONS_FILE, encoding="utf-8") as f:
    for row in csv.DictReader(f):
        choices = {str(i): row[f"choice_{i}"] for i in range(1, 11)}
        questions.append({"id": row["id"], "question": row["question"], "choices": choices})
print(f"Loaded {len(questions)} questions")

"""## Section 8: Run Ensemble (3 rounds)

"""

print("=" * 60)
print(f"ENSEMBLE: 3 prompt styles × {N_QUESTIONS} questions")
print(f"LLM: {LLM_MODEL}+fallback | Embed: {EMBED_MODEL_NAME}")
print("=" * 60)

STYLES = [
    ("A_analytical", PROMPT_A_SYSTEM),
    ("B_keyword",    PROMPT_B_SYSTEM),
    ("C_cot",        PROMPT_C_SYSTEM),
]

all_predictions = {name: {} for name, _ in STYLES}
final_predictions = {}

t0 = time.time()

for i, q in enumerate(questions[:N_QUESTIONS]):
    qid = q["id"]
    question = q["question"]

    # Step 1: Not-related check (heuristic — proven to work)
    if is_not_related(question):
        for name, _ in STYLES:
            all_predictions[name][qid] = 10
        final_predictions[qid] = 10
        print(f"  Q{qid}: NOT RELATED → 10 (all)")
        continue

    # Step 2: Retrieve ONCE
    chunks = get_chunks_for_question(q)
    if chunks is None:
        for name, _ in STYLES:
            all_predictions[name][qid] = 10
        final_predictions[qid] = 10
        continue

    comp_info = ""
    products = detect_products(question)
    if is_comparison(question) and len(products) >= 2:
        comp_info = f" Comp[{','.join(products[:3])}]→{len(chunks)}"

    # Step 3: Generate with 3 styles
    answers = []
    answer_details = []
    for name, sys_prompt in STYLES:
        ans = generate_answer(question, q["choices"], chunks, sys_prompt)
        if ans is None:
            ans = 9
        all_predictions[name][qid] = ans
        answers.append(ans)
        answer_details.append(f"{name[0]}={ans}")
        time.sleep(0.2)

    # Step 4: Majority vote
    final = majority_vote(answers)
    final_predictions[qid] = final

    # Show agreement
    agree = "✓" if len(set(answers)) == 1 else f"VOTE"
    print(f"  Q{qid}: {' '.join(answer_details)} → {final} [{agree}]{comp_info}")

    # Auto-save every 10
    if (i + 1) % 10 == 0:
        elapsed = time.time() - t0
        rate = (i + 1) / elapsed * 60 if elapsed > 0 else 0
        with open("submission_partial.csv", "w", newline="", encoding="utf-8") as f:
            w = csv.writer(f)
            w.writerow(["id", "answer"])
            for qq in questions[:N_QUESTIONS]:
                w.writerow([qq["id"], final_predictions.get(qq["id"], 1)])
        print(f"\n  --- {i+1}/{N_QUESTIONS} ({rate:.0f} q/min) | saved ---\n")

elapsed = time.time() - t0
print(f"\nDone! {elapsed:.0f}s ({elapsed/N_QUESTIONS:.1f}s/q)")

"""## Section 9: Analysis & Submit

"""

# Agreement analysis
agree_count = 0
vote_count = 0
for qid in final_predictions:
    answers = [all_predictions[name][qid] for name, _ in STYLES]
    if len(set(answers)) == 1:
        agree_count += 1
    else:
        vote_count += 1

print(f"\nAgreement: {agree_count} unanimous / {vote_count} voted / {N_QUESTIONS} total")
print(f"Agreement rate: {agree_count/N_QUESTIONS*100:.0f}%")

# Distribution
dist = Counter(final_predictions.values())
print("\nFinal distribution:")
for ans in sorted(dist.keys()):
    bar = "█" * dist[ans]
    label = {9: " (not in KB)", 10: " (not related)"}.get(ans, "")
    print(f"  {ans:>2}: {dist[ans]:>3} {bar}{label}")

# Per-style distribution
print("\nPer-style distributions:")
for name, _ in STYLES:
    d = Counter(all_predictions[name].values())
    c9 = d.get(9, 0)
    c10 = d.get(10, 0)
    print(f"  {name}: choice9={c9}, choice10={c10}")

# === FINAL SUBMISSION ===
with open("submission.csv", "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f)
    w.writerow(["id", "answer"])
    for q in questions[:N_QUESTIONS]:
        w.writerow([q["id"], final_predictions.get(q["id"], 1)])
print("submission.csv saved!")

# Also save individual style results for analysis
for name, _ in STYLES:
    fname = f"submission_{name}.csv"
    with open(fname, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["id", "answer"])
        for q in questions[:N_QUESTIONS]:
            w.writerow([q["id"], all_predictions[name].get(q["id"], 1)])
    print(f"  {fname} saved")

# Show disagreement details
print("\n=== Disagreements (where voting matters) ===")
for q in questions[:N_QUESTIONS]:
    qid = q["id"]
    answers = [all_predictions[name][qid] for name, _ in STYLES]
    if len(set(answers)) > 1:
        detail = " ".join(f"{name[0]}={all_predictions[name][qid]}" for name, _ in STYLES)
        print(f"  Q{qid}: {detail} → VOTED {final_predictions[qid]}  | {q['question'][:50]}")